# Generated by Django 4.1.4 on 2022-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En curso'), ('3', 'Cerrado')], max_length=1)),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'db_table': 'notas',
            },
        ),
    ]
